name: auto_start
description: >
  A Flutter plugin to automatically launch the app on device boot and 
  keep it alive on Android TV or similar embedded systems.

version: 1.0.1

maintainer: Gadeley Georgy Constant <gadeleygeorgy.constant1@uniq.edu>

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.trendcatchadvertising.digitaldisplay
        pluginClass: AutoStartPlugin

# (facultatif, pour pub.dev)
homepage: https://trendcatchadvertising.com
repository: https://github.com/trendcatch/auto_start_plugin
